### ISSUE TITLE
ทดสอบ train madel ผ่าน colab ติด error

### ISSUE THREAD

**Issue by cworajak** [vistec-AI/vistec-ser#5]
ผมทำการ train model ผ่าน colab ติด error อยู่ 2 ขั้นตอน ครับ
1. ขั้นตอน Visualize Training
- ไม่สามารถแสดงผลผ่าน Web browser ได้ ขึ้น error 403
2. ขั้นตอน Evaluating Model
- ขึ้น error ModuleNotFoundError: No module named 'pytorch_lightning.metrics'
ขอคำแนะนำด้วยครับ

**Comment by tann9949** [comment]
Errors are fixed. Please check whether code run correctly.
